cart/urls.py
from django.urls import path
from . import views

#from .views import confirmation
from .views import checkout
from .views import information
from .views import successful
from .views import confirmation_view





urlpatterns = [
    path('', views.index, name="cart-index"),

    path('confirmation/', views.confirmation_view, name='confirmation'),
    path('successful/', views.successful, name='successful'),
    path('information/', views.information, name='information'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/clear/', views.clear_cart, name='clear-cart'),
#    path('<int:id>', views.get_cart_by_id, name="cart_details"),
#    path('create_cart', views.create_cart, name="create_cart")
]

    #path('confirmation/', views.confirmation, name='confirmation'),
    #path('checkout/', views.checkout, name='checkout'),
    #path('<int:id>', views.get_cart_by_id, name="cart_details"),
    #path('create_cart', views.create_cart, name="create_cart"),
    #path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    #path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    #path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    #path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    #path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    #path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('menus/', include('menu.urls')),
    path('carts/', include('cart.urls')),
    path('homes/', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', LoginView.as_view(next_page='profile', template_name='user/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('profile', views.profile, name='profile')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# class CardInfo(models.Model):
#     card_number
#     cvv =
#     date =

    # -username
    # -password




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True)

    def __str__(self):
        return self.name

user/forms/profile_form.py
from django.forms import ModelForm, widgets, FileInput
from user.models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['id']
        widgets = {
            'profile_image': widgets.FileInput(attrs={}),
            'name': widgets.TextInput(attrs={'class': 'text_box'}),
            'user': widgets.HiddenInput()
        }

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from user.forms.profile_form import ProfileForm
from django.contrib.auth.decorators import login_required
from user.models import Profile
import time
from PIL import Image

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    return render(request, 'user/register.html', {
        'form': UserCreationForm()
    })

@login_required
def profile(request):
    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = ProfileForm(instance=profile, data=request.POST, files=request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()

            # Resize and save profile image
            if profile.profile_image:
                image = Image.open(profile.profile_image.path)
                output_size = (480, 480)
                image.thumbnail(output_size)
                image.save(profile.profile_image.path)
            return redirect('profile')
    else:
        form = ProfileForm(instance=profile, initial={'user': request.user})
    return render(request, 'user/profile.html', {'form': form})

templates/user/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>

    <form method="post" class="form form-horizontal">
    <h1>Login</h1>
        {% csrf_token %}
        {{ form }}
    <input type="submit" class="btn btn-primary login" value="Login"/>
        <p>Don't have an account?</p>
        <a href="">
        <a class="reg" href="{% url 'register' %}">Register here!</a>
            </a>
    </form>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>
    <h1>Profile</h1>
    <form class="form form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'profile' %}">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">

        {% csrf_token %}

        {{ form }}


            </div>

        </div>
    <img src="{{user.profile.profile_image.url}}" class="profile_image" id="id_profile_image"/>
        <input type="submit" class="btn btn-primary" value="update"/>
               </form>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <form class="form form-horizontal" method="post">
    <h1> Sign up</h1>
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary signup" value="Sign up" />
    </form>


{% endblock %}